theme = "native.toml"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "net"
device = "tun0"
hide_missing = true
format = "STG {speed_down;K*b}"
interval = 5

[[block]]
block = "net"
device = "tun1"
hide_missing = true
format = "PRD {speed_down;K*b}"
interval = 5

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}"
scale = "celsius"
chip = "coretemp-isa-*"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "networkmanager"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+", "tun\\d+", "virbr\\d+"]
interface_name_include = []
ap_format = "{ssid^10}"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
