FROM fedora:latest                                                                                                                                             
RUN dnf -y update && dnf -y install zsh git vim tmux weechat && dnf clean all                                                                                  
CMD zsh 
