- name: Check if docker present
  stat:
    path: /usr/bin/docker
  register: docker_present_stat
  tags:
      - docker

- name: Install docker dependencies
  dnf:
    name:
      - dnf-plugins-core
    state: "present"
  register: result
  until: result is not failed
  tags:
    - docker

- name: add docker repo
  shell: "dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo"
  when: not docker_present_stat.stat.exists
  tags:
    - docker

- name: Install docker
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: "present"
  when: not docker_present_stat.stat.exists
  tags:
    - docker

# TODO: username to var
- name: Add current user to docker group
  user: name="sean" groups=docker append=yes
  tags:
      - docker

- name: Start and enable docker service
  service: name=docker state=restarted enabled=yes
  tags:
      - docker

- name: Check if docker-compose is installed
  stat:
    path: /usr/local/bin/docker-compose
  register: _docker_compose_binary
  tags:
      - docker

#TODO: understand when clause here..
- name: Download and install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
  when: _docker_compose_binary is defined
  tags:
      - docker

- name: Set chmod +x on docker-compose
  file:
    dest: /usr/local/bin/docker-compose
    mode: a+x
  when: _docker_compose_binary is defined
  tags:
      - docker
