- name: Install python build dependencies
  tags:
    - python
  dnf: 
    name:
      - make 
      - gcc 
      - zlib-devel 
      - bzip2 
      - bzip2-devel 
      - readline-devel 
      - sqlite 
      - sqlite-devel 
      - openssl-devel 
      - tk-devel 
      - libffi-devel 
      - xz-devel
    state: latest

- name: Install pyenv
  become: no
  git:
    repo: "https://github.com/pyenv/pyenv.git"
    dest: "~/.pyenv"
    version: master
  tags: 
    - python

- name: check pyenv-virtualenv installed
  become: no
  stat:
    path: "~/.pyenv/plugins/pyenv-virtualenv"
  register: pyenv_virtualenv
  tags: 
    - python

- name: git clone pyenv-virtualenv
  git: 
    repo: https://github.com/pyenv/pyenv-virtualenv
    dest: "~/.pyenv/plugins/pyenv-virtualenv"
  become: no
  when: pyenv_virtualenv.stat.exists == false
  tags: 
    - python

- name: Install pipx
  become: no
  tags: 
    - python
  shell: "PYENV_VERSION=system python3 -m pip install --user pipx"
  args:
    creates: "~/.local/bin/pipx"
  tags: 
    - python

- name: Install poetry
  become: no
  tags:
    - python
  shell: "PYENV_VERSION=system python3 -m pipx install poetry"
  args:
    creates: "~/.poetry/bin/poetry"

- name: Install some tools via pipx
  become: no
  tags:
    - python
  shell: "PYENV_VERSION=system python3 -m pipx install awscli awslogs streamlink jupyterlab"
