- name: Install python build dependencies
  become: yes
  tags:
    - python
  dnf:
    name:
      - make
      - gcc
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - tk-devel
      - libffi-devel
      - xz-devel
    state: latest

- name: Install pyenv
  become: no
  git:
    repo: "https://github.com/pyenv/pyenv.git"
    dest: "$HOME/.pyenv"
    version: master
  tags:
    - python

- name: check pyenv-virtualenv installed
  become: no
  stat:
    path: "$HOME/.pyenv/plugins/pyenv-virtualenv"
  register: pyenv_virtualenv
  tags:
    - python

- name: git clone pyenv-virtualenv
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv
    dest: "$HOME/.pyenv/plugins/pyenv-virtualenv"
  become: no
  when: pyenv_virtualenv.stat.exists == false
  tags:
    - python

- name: Ensure pip is available
  shell: "PYENV_VERSION=system python3 -m ensurepip --user"
  tags:
    - python

- name: Install pipx
  become: no
  tags:
    - python
  shell: "PYENV_VERSION=system python3 -m pip install --user pipx"
  args:
    creates: "$HOME/.local/bin/pipx"
  tags:
    - python

- name: Install poetry
  become: no
  tags:
    - python
  shell: "PYENV_VERSION=system python3 -m pipx install poetry"
  args:
    creates: "$HOME/.local/pipx/venvs/poetry"

- name: Install some tools via pipx
  shell: "PYENV_VERSION=system python3 -m pipx install {{ item }}"
  with_items:
    - black
    - jupyterlab
    - streamlink
    - awslogs
    - awscli
  become: no
  args:
    creates: "~/.local/pipx/venvs/{{ item }}"
  tags:
    - python
