- name: Check if rustup is installed
  become: no
  stat:
    path: "$HOME/.cargo/bin/rustup"
  register: rustup_stat
  tags:
    - rust

- name: Download rustup.sh
  become: no
  get_url:
    url: https://sh.rustup.rs
    dest: "/tmp/rustup.sh"
    mode: 0755
  when: not rustup_stat.stat.exists
  tags:
    - rust

- name: Install rustup using rustup.sh
  become: no
  command: /tmp/rustup.sh -y
  args:
    creates: "$HOME/.cargo/bin/rustup"
  when: not rustup_stat.stat.exists
  tags:
    - rust

- name: Ensure existing rustup-managed components are up to date
  become: no
  command: $HOME/.cargo/bin/rustup update
  register: rustup_update
  changed_when: "'updated' in rustup_update.stdout"
  tags:
    - rust

- name: See which cargo packages are installed
  shell: "$HOME/.cargo/bin/cargo install --list | awk '$0 ~ /^[a-zA-Z]/ { print $1 }'"
  become: no
  register: cargo_pkgs
  changed_when: false
  tags:
    - rust

- name: Install rust utilities
  command: "$HOME/.cargo/bin/cargo install --locked {{ item }}"
  with_items:
    - hyperfine
    - ripgrep
    - cargo-update
    - fd-find
    - exa
    - bat
    - git-trim
    - git-absorb
    - starship
    - xsv
    - alacritty
    - git-delta
    - flavours
  become: no
  when: 'item not in cargo_pkgs.stdout_lines'
  tags:
    - rust

# needs dbus-1
- name: Install i3status-rust
  command: "$HOME/.cargo/bin/cargo install --locked --git https://github.com/greshake/i3status-rust --tag v0.20.3"
  become: no
  when: '"i3status-rs" not in cargo_pkgs.stdout_lines'
  tags:
    - rust
