- name: Define Fedora major version number
  set_fact:
    fedora_version: "{{ hostvars['localhost'].ansible_distribution_major_version }}"
  tags:
    - install

- name: Check for RPM Fusion repo
  stat:
    path: '/etc/yum.repos.d/rpmfusion-free.repo'
  register: rpmfusion_repo
  tags:
    - install

- name: Enable access to RPM Fusion repos
  dnf:
    disable_gpg_check: yes
    name:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"
  when: not rpmfusion_repo.stat.exists
  tags:
    - install

# TODO: split packages up (e.g python build deps etc, applications, buid tools)
        #- neomutt
# dbus-devel livecd-tools smartmontools exfatprogs ninja-build
# patch gettext zbar libtiff-devel mg libjpeg-devel file-devel
# fuse-devel mg
# ntfs-3g-devel ntfs-3g
# guix
# clang clang9.0-devel
# gmp-devel libffi zlib-devel xz ghc
# libxslt-devel
# libseccomp-devel jansson-devel libyaml-devel libxml2-devel
# acpi_call
# tlp tlp-rdw
# lm_sensors sxiv texlive-scheme-full xbacklight powertop tlp zathura-pdf-mupdf

- name: Install system packages
  dnf:
    name:
      - vlc
      - firefox
      - firefox-wayland
      - tar
      - unzip
      - weechat
      - chromium


- name: Install system packages
  dnf:
    name:
      - zsh
      - vim
      - git
      - htop
      - nmap
      - tmux
      - jq
      - ffmpeg
      - lm_sensors
      - alsa-firmware
      - alsa-plugins-pulseaudio
      - pulseaudio-utils
      - alsa-lib
      - alsa-utils
      - amixer
      - openssl
      - telnet
      - ftp
      - openvpn-devel
      - NetworkManager-openvpn
      - dbus-devel-1
      - dbus-1
      - rclone
      - rsync
      - gcc-c++
      - ShellCheck
      - make
      - cmake
      - podman
      - sway
      - swayidle
      - swaylock
      - grim
      - slurp
      - mako
      - restic
      - youtube-dl
      - mpv
      - wf-recorder
      - lapack-devel
      - pandoc
      - blas-devel
      - screenfetch
      - readline-devel
      - wl-clipboard
      - libtool
      - autoconf
      - pkgconf
      - gcc
      - openssl-devel
      - rofi
      - sqlite
      - sqlite-devel
      - zathura
      - zathura-pdf-mupdf
      - nfs-utils
      - zlib-devel
      - acpi
      - fuse
      - exfat-utils
      - libffi-devel
      - bzip2
      - bzip2-devel
      - pavucontrol
      - postgresql
      - fontconfig
      - freetype-devel
      - fontconfig-devel
      - stow
      - ranger
      - libxcb-devel
      - libxkbcommon-devel
      - g++
      - light
      - adobe-source-code-pro-fonts
      - mupdf
      - imv
      - isync
      - msmtp
      - unrar
      - wkhtmltopdf
      - ansible
      - gnupg
      - prename
      - automake
      - diffpdf
      - perl
      - neovim
    state: latest
