format = """
$username$hostname$directory$git_branch $python\n\\$ """

add_newline = false

[hostname]
disabled = false
ssh_only = false
format =  "[$hostname](red):"

[username]
disabled = false
show_always = true
style_user = "white blue"
format = "[$user]($style)@"

[directory]
style = "blue"
truncation_length = 8
truncate_to_repo = false

[git_branch]
style = ""
only_attached = true
format = "[git:]()([$branch]($style))"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)'
