- hosts: localhost
  become: yes
  tasks:
    #- include: tasks/sys.yml
    - include: tasks/python.yml
    #- include: tasks/docker.yml
    - include: tasks/rust.yml
    #- include: tasks/golang.yml
    #- include: tasks/shell.yml

    # TODO: look at latest calls for tlp https://linrunner.de/tlp/installation/fedora.html

    - name: Check if volta is installed
      become: no
      stat:
        path: "$HOME/.volta/bin/volta"
      register: volta_stat

    - name: Get volta script
      become: no
      get_url:
        url: https://get.volta.sh
        dest: "/tmp/volta.sh"
      when: not volta_stat.stat.exists

    # needs openssl
    - name: Install volta
      become: no
      command: /tmp/volta.sh --skip-setup
      args:
        creates: "$HOME/.volta/bin/volta"
      when: not volta_stat.stat.exists

    - name: Check if /usr/bin/pass exists
      become: yes
      stat:
        path: "/usr/bin/pass"
      register: pass_stat

    - name: Get pass tarball
      become: no
      get_url:
        url: https://git.zx2c4.com/password-store/snapshot/password-store-1.7.4.tar.xz
        force: no
        dest: "/tmp/password-store.tar.xz"
      when: not pass_stat.stat.exists

    # needs unzip + lzma
    - name: Unpack pass tarball
      become: yes
      unarchive: src=/tmp/password-store.tar.xz dest=/tmp
      when: not pass_stat.stat.exists

    - name: Install pass
      become: yes
      make:
        chdir: "/tmp/password-store-1.7.4"
        target: install
      when: not pass_stat.stat.exists
